// File generated by flutterfire_cli
// This file will be automatically generated when you run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Check if Firebase configuration is valid (not using placeholder values)
  static bool get isConfigured {
    final options = currentPlatform;
    return !options.apiKey.startsWith('YOUR_') &&
        !options.appId.startsWith('YOUR_') &&
        !options.projectId.startsWith('YOUR_');
  }

  static FirebaseOptions get currentPlatform {
    // Web platform detection
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjfcD8Rws6llDbNPrG_cSuGS6BpjJpHE',
    appId: '1:281741019162:android:d826aacfb8a150227f69a3',
    messagingSenderId: '281741019162',
    projectId: 'qr-code-scranner--247',
    storageBucket: 'qr-code-scranner--247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFe2mvCI3jDsOneIJgtBNF2tPLmZ-PHPk',
    appId: '1:281741019162:ios:1bd6d191dd6dc79d7f69a3',
    messagingSenderId: '281741019162',
    projectId: 'qr-code-scranner--247',
    storageBucket: 'qr-code-scranner--247.firebasestorage.app',
    iosBundleId: 'com.example.qrCodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFe2mvCI3jDsOneIJgtBNF2tPLmZ-PHPk',
    appId: '1:281741019162:ios:1bd6d191dd6dc79d7f69a3',
    messagingSenderId: '281741019162',
    projectId: 'qr-code-scranner--247',
    storageBucket: 'qr-code-scranner--247.firebasestorage.app',
    iosBundleId: 'com.example.qrCodeScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFSkVO7D0WLwnsEAiqGl8Q73_Bjxq3etM',
    appId: '1:281741019162:web:966e5bb3a1ef16957f69a3',
    messagingSenderId: '281741019162',
    projectId: 'qr-code-scranner--247',
    authDomain: 'qr-code-scranner--247.firebaseapp.com',
    storageBucket: 'qr-code-scranner--247.firebasestorage.app',
    measurementId: 'G-PMVQE09K0K',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFSkVO7D0WLwnsEAiqGl8Q73_Bjxq3etM',
    appId: '1:281741019162:web:aedb1d273360bfc77f69a3',
    messagingSenderId: '281741019162',
    projectId: 'qr-code-scranner--247',
    authDomain: 'qr-code-scranner--247.firebaseapp.com',
    storageBucket: 'qr-code-scranner--247.firebasestorage.app',
    measurementId: 'G-GZ2LS9YDET',
  );
}
